### ISSUE TITLE
No alasql persistent entries under /tmp/redlink

### ISSUE THREAD

**Issue by giminni** [Gippsman2017/node-red-contrib-redlink#4]
**Describe the bug** *A clear and concise description of what the bug is.*
After restarting the producer node no info regarding the consumer service available

**To Reproduce** *Steps to reproduce the behavior:*
- Define two docker container with exposed ports 2000 (Producer node) and 2001 (Consumer node)
- Connect consumer node to producer node as a peer
- Reload producer node
- Producer message cannot be transited to consumer node, because has lost the route

**Expected behavior** *A clear and concise description of what you expected to happen.*
- AlaSQL has a persistent store in /tmp/redlink
- No reload problems

- Handle reload of routes transparently in memory mode

**Screenshots** *If applicable, add screenshots to help explain your problem.*

**Additional context** *Add any other context about the problem here.*
- /tmp/redlink is empty no route information stored so far

**Comment by Gippsman2017** [comment]
Thanks for this, much appreciated, confirmed, there are a number of bugs in this issue, we are working on them all. BTW, /tmp/redlink is only used whilst the message is in transit during notify and before read, not all messages are here, small messages are held in memory, usually less than 25K (post base64 encoded).

**Comment by Gippsman2017** [comment]
A Major re-write of the reSync process and a new timer added (30 secs) to cater for stores that connect and disconnect.
We have tested this in a 3 container setup where a producer container and a consumer container connects to a common north bound container .
Attached is a simple flow to check the updates.
N**ote that a further update is currently in test for Consumer cascade deletes, so, this will remove consumers that are no longer in the mesh, but stuck in different stores.**
[redlink-test4.tar.gz](https://github.com/Gippsman2017/node-red-contrib-redlink/files/3624715/redlink-test4.tar.gz)
