### ISSUE TITLE
Redlink picture/architecture not clear 

### ISSUE THREAD

**Issue by giminni** [Gippsman2017/node-red-contrib-redlink#5]
I am missing a clear definition: 
1) how the producer are coupled with the consumer and how the data flows between **producer ->local store -> network -> remote store -> consumer**
2) What should be configured in redlink to make this happen
3) Can we use one local store for bidirectional communication or should be producer and consumer dedicated nodes?
4) Example how to setup two docker/kubernetes containers with one producer container/pod and one scalable consumer container/pod

It was hard to figure out that the consumer store must have a north peer for advertising the service to the producer node and not vice versa.

**Comment by Gippsman2017** [comment]
I have updated a picture / matrix, but essentially, any north store that has a south store connected to it, will transit notification messages. we will add many more examples to explain how you can configure the Redlink networks up. As far as dedicated nodes for producer / consumers, its up to you, check out the matrix, you can add a producer to any store, visibility is based on where you place the producer and how you place and configure the connections between stores.
